fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: local
    hooks:
    -   id: build-and-analyse-with-polyspace
        name: build-and-analyse-with-polyspace
        entry: sh -x build_script.sh
        language: system
        always_run: true
        pass_filenames: false
    -   id: perform-sqo-verification
        name: perform-sqo-verification
        entry: python sqo_manager.py
        language: python
        description: Evaluates if changed files meet expected software quality objective
        always_run: true
        pass_filenames: false
